- name: Setup packages
  hosts: all
  gather_facts: yes

  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Deploy Redmine
      # Используем модуль community.docker.docker_container
      community.docker.docker_container:
        name: redmine
        image: redmine
        # Публикуемые порты. Слева порт внутри контейнера,
        # справа порт по которому он будет доступен снаружи
        published_ports: 3000:3000
        restart_policy: always
        container_default_behavior: no_defaults
        pull: yes
        env:
          REDMINE_DB_POSTGRES: "{{db_host}}"
          REDMINE_DB_PORT: "{{db_port}}"
          REDMINE_DB_USERNAME: "{{db_user}}"
          REDMINE_DB_PASSWORD: "{{db_password}}"
          REDMINE_DB_DATABASE: "{{data_base}}"
          REDMINE_SECRET_KEY_BASE: "{{redmine_secret_key}}"

  roles:
    - { role: geerlingguy.pip, become: yes }


- name: Setup monitoring
  hosts: webservers
  roles:
    - { role: datadog.datadog, become: yes }
